name = "MovingRings"
uuid = "3594f790-2b65-4114-995e-a369a7faa39f"
authors = ["Jeffrey A. Sarnoff <jeffrey.sarnoff@gmail.com>"]
version = "0.1.0"

[deps]

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
